<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>IcyFre Codex Studio</Title>
    <AssemblyTitle>IcyFre Codex Studio</AssemblyTitle>
    <Product>IcyFre Codex Studio</Product>
    <Company>IcyFre</Company>
  </PropertyGroup>
</Project>
